[ADD] minimal /TeX folder

diff --git a/Dockerfile2 b/Dockerfile2
--- a/Dockerfile2
+++ b/Dockerfile2
@@ -15,7 +15,9 @@ RUN \
             libnss3 \
             # Install Chrome dependencies.
             dbus-x11 \
-            uuid-runtime
+            uuid-runtime\
+            # Tex dependancies
+            fontconfig wget make
 
 RUN \
       apt-get install -y --no-install-recommends software-properties-common && \
@@ -48,14 +50,58 @@ RUN \
 \
       pip3 list --outdated && \
 \
-   echo "**** Latex PDF ****" && \
-\
-      apt-get install -y --no-install-recommends \
-      latexmk texlive-fonts-recommended texlive-lang-french texlive-latex-extra texlive-latex-recommended tex-gyre && \ 
-\
+   echo "**** Latex PDF ****"
+
+RUN mkdir /TeX
+
+WORKDIR /TeX
+
+COPY  texlive.profile tex-pkgs.txt /TeX/
+
+# Install some basic collections
+RUN   apt-get update -qy &&\
+   # Install necessary certificate?
+   apt-get install -f -qy --no-install-recommends apt-utils || exit 1 &&\
+   # get and update certificates, to hopefully resolve mscorefonts error
+   apt-get install -f -qy --no-install-recommends ca-certificates || exit 1  &&\
+   update-ca-certificates &&\
+   rm -rf /var/lib/apt/lists/* &&\
+   apt-get clean
+
+# Install newest TeXLive
+RUN   TAR="http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz" &&\
+   wget -nv $TAR && tar -xvf *.tar.gz && \
+   mkdir texlive && cd texlive &&\
+   TEXLIVE_INSTALL_ENV_NOCHECK=true TEXLIVE_INSTALL_NO_WELCOME=true \
+   ../install-tl-*/install-tl --profile=../texlive.profile && cd bin/* &&\
+   ./tlmgr install latex-bin xetex latexmk latexdiff &&\
+   # Install custom packages
+        ./tlmgr install $(cat /TeX/tex-pkgs.txt | tr "\n" " ") &&\
+   # Clean up insallation
+        cd /TeX/ &&\
+   rm -rf install-tl-* textlive.profile tex-pkgs.txt
+
+# where to find the bin
+ENV PATH="/TeX/texlive/bin/x86_64-linux/:${PATH}"
+
+# Install git-latexdiff
+RUN   git clone https://gitlab.com/git-latexdiff/git-latexdiff.git /tmp/gld &&\
+   cp /tmp/gld/git-latexdiff /TeX/texlive/bin/x86_64-linux/ &&\
+   chmod a+x /TeX/texlive/bin/x86_64-linux/git-latexdiff &&\
+   rm -rf /tmp/gld
+
+# update fontutils and lua
+# RUN     fc-cache -fv || exit 1 &&\
+   # texhash --verbose ||exit 1
+
+#      apt-get install -y --no-install-recommends \
+#      latexmk texlive-fonts-recommended texlive-lang-french texlive-latex-extra texlive-latex-recommended tex-gyre && \
+
+WORKDIR /
+
+RUN \
    echo "**** cleanup ****" && \
-      apt-get autoremove -y && \
-      apt-get autoclean && \
+      apt-get clean && \
       rm -rf \
       /var/cache/* \
       /var/lib/apt/lists/* \
@@ -85,6 +131,8 @@ ENV \
 
 # add local files
 COPY root/ /
+
+WORKDIR $HOME
 
 EXPOSE 8080
 EXPOSE 27123
